export const ENV_CONFIGURATION = {
  // Environment
  NODE_ENV: 'NODE_ENV',
  API_PORT: 'API_PORT',

  // EXTERNAL HTTP PROVIDERS
  CALORIES_NINJA_URL: 'CALORIES_NINJA_URL',
  CALORIES_NINJA_API_KEY: 'CALORIES_NINJA_API_KEY',
} as const;
