// This file is auto-generated by @hey-api/openapi-ts

export const $MacroTotalOutput = {
  type: 'object',
  properties: {
    calories: {
      type: 'number',
      description: 'Total calories',
      example: 100,
    },
    carbohydrates: {
      type: 'number',
      description: 'Total carbohydrates',
      example: 10,
    },
    fats: {
      type: 'number',
      description: 'Total fats',
      example: 10,
    },
    proteins: {
      type: 'number',
      description: 'Total proteins',
      example: 10,
    },
  },
  required: ['calories', 'carbohydrates', 'fats', 'proteins'],
} as const;

export const $NutritionalValuesServingOutput = {
  type: 'object',
  properties: {
    size: {
      type: 'number',
      description: 'Serving size',
      example: 100,
      minimum: 0,
    },
    unit: {
      type: 'string',
      description: 'Serving unit',
      example: 'GRAMS',
      enum: ['GRAMS', 'UNIT'],
    },
  },
  required: ['size', 'unit'],
} as const;

export const $NutritionalValuesItemsOutput = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      description: 'Name of the nutritional value',
      example: 'Apple',
    },
    macros: {
      $ref: '#/components/schemas/MacroTotalOutput',
    },
    serving: {
      $ref: '#/components/schemas/NutritionalValuesServingOutput',
    },
  },
  required: ['name', 'macros', 'serving'],
} as const;

export const $GetNutritionalValuesByTextOutput = {
  type: 'object',
  properties: {
    total: {
      $ref: '#/components/schemas/MacroTotalOutput',
    },
    items: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/NutritionalValuesItemsOutput',
      },
    },
  },
  required: ['total', 'items'],
} as const;

export const $ApiException = {
  type: 'object',
  properties: {
    code: {
      type: 'string',
      description: 'The error code, shared between client and server.',
      example: 'ERROR:INTERNAL_SERVER_ERROR',
      enum: ['ERROR:INTERNAL_SERVER_ERROR', 'ERROR:VALIDATION', 'ERROR:NUTRITIONAL_VALUES__NOT_FOUND'],
    },
    data: {
      type: 'object',
      description: 'Additional data to return to the client.',
      example: {
        property: 'value',
      },
    },
    message: {
      type: 'string',
      description: 'The error message to return to the client.',
      example: 'Internal server error',
    },
  },
  required: ['code', 'message'],
} as const;
