// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { MobileGetAllByTextData, MobileGetAllByTextResponse } from './types.gen';

/**
 * Get nutritional values by text
 * @param data The data for the request.
 * @param data.searchText
 * @returns GetNutritionalValuesByTextOutput Nutritional values fetched successfully.
 * @throws ApiError
 */
export const mobileGetAllByText = (data: MobileGetAllByTextData): CancelablePromise<MobileGetAllByTextResponse> => {
  return __request(OpenAPI, {
    method: 'GET',
    url: '/mobile/nutritional-values/all/by-text/{searchText}',
    path: {
      searchText: data.searchText,
    },
    errors: {
      401: 'The request has not been processed because it lacks valid authentication credentials.',
      403: 'The request has not been processed because it lacks valid authorization credentials.',
      404: 'The requested resource could not be found.',
    },
  });
};
