// This file is auto-generated by @hey-api/openapi-ts

export type MacroTotalOutput = {
  /**
   * Total calories
   */
  calories: number;
  /**
   * Total carbohydrates
   */
  carbohydrates: number;
  /**
   * Total fats
   */
  fats: number;
  /**
   * Total proteins
   */
  proteins: number;
};

export type NutritionalValuesServingOutput = {
  /**
   * Serving size
   */
  size: number;
  /**
   * Serving unit
   */
  unit: 'GRAMS' | 'UNIT';
};

/**
 * Serving unit
 */
export type unit = 'GRAMS' | 'UNIT';

export type NutritionalValuesItemsOutput = {
  /**
   * Name of the nutritional value
   */
  name: string;
  macros: MacroTotalOutput;
  serving: NutritionalValuesServingOutput;
};

export type GetNutritionalValuesByTextOutput = {
  total: MacroTotalOutput;
  items: Array<NutritionalValuesItemsOutput>;
};

export type ApiException = {
  /**
   * The error code, shared between client and server.
   */
  code: 'ERROR:INTERNAL_SERVER_ERROR' | 'ERROR:VALIDATION' | 'ERROR:NUTRITIONAL_VALUES__NOT_FOUND';
  /**
   * Additional data to return to the client.
   */
  data?: {
    [key: string]: unknown;
  };
  /**
   * The error message to return to the client.
   */
  message: string;
};

/**
 * The error code, shared between client and server.
 */
export type code = 'ERROR:INTERNAL_SERVER_ERROR' | 'ERROR:VALIDATION' | 'ERROR:NUTRITIONAL_VALUES__NOT_FOUND';

export type MobileGetAllByTextData = {
  searchText: string;
};

export type MobileGetAllByTextResponse = GetNutritionalValuesByTextOutput;

export type $OpenApiTs = {
  '/mobile/nutritional-values/all/by-text/{searchText}': {
    get: {
      req: MobileGetAllByTextData;
      res: {
        /**
         * Nutritional values fetched successfully.
         */
        200: GetNutritionalValuesByTextOutput;
        /**
         * The request has not been processed because it lacks valid authentication credentials.
         */
        401: ApiException;
        /**
         * The request has not been processed because it lacks valid authorization credentials.
         */
        403: ApiException;
        /**
         * The requested resource could not be found.
         */
        404: ApiException;
      };
    };
  };
};
